a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Controllers/Common/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Areas.Admin.Controllers.Common
{
    [Authorize(Roles = "Manager, Admin"), Area("Admin")]
    public class AdminController : Controller
    {
    }
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Controllers/ProductsController.cs
using a5pwt_ctvrtek.Application.ApplicationServices.Products;
using a5pwt_ctvrtek.Application.ViewModels.Products;
using a5pwt_ctvrtek.Areas.Admin.Controllers.Common;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Areas.Admin.Controllers
{
    public class ProductsController : AdminController
    {
        private readonly IProductApplicationService _productApplicationService;

        public ProductsController(IProductApplicationService productApplicationService)
        {
            _productApplicationService = productApplicationService;
        }

        public IActionResult Index()
        {
            var vm = _productApplicationService.GetIndexViewModel();
            return View(vm);
        }

        public IActionResult Edit(int id)
        {
            var vm = _productApplicationService.GetProductViewModel(id);
            return View(vm);
        }

        [HttpPost]
        public IActionResult Edit(ProductViewModel model)
        {
            var product = _productApplicationService.Edit(model);

            return Json(product);
        }

        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(ProductViewModel model)
        {
            var product = _productApplicationService.Insert(model);

            return Json(product);
        }

        public IActionResult Delete(ProductViewModel model)
        {
            _productApplicationService.Delete(model);

            return RedirectToAction(nameof(Index));
        }
    }
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using a5pwt_ctvrtek.Application.ApplicationServices.Security;
using a5pwt_ctvrtek.Application.ViewModels.Security;
using a5pwt_ctvrtek.Areas.Admin.Controllers.Common;
using a5pwt_ctvrtek.Domain.Constants;
using a5pwt_ctvrtek.Infrastructure.Identity.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Areas.Admin.Controllers
{
    [AllowAnonymous]
    public class SecurityController : AdminController
    {
        private readonly ISecurityApplicationService _securityApplicationService;

        public SecurityController(ISecurityApplicationService securityApplicationService)
        {
            _securityApplicationService = securityApplicationService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            var result = await _securityApplicationService.Login(vm);
            if (result)
            {
                var user = await _securityApplicationService.GetUserByEmail(vm.Login);
                var roles = await _securityApplicationService.GetUserRoles(user);
                if (roles.Contains(Roles.Admin) || roles.Contains(Roles.Manager))
                    return RedirectToAction("Index", "Products", new { area = "Admin" });
                return RedirectToAction("Index", "Products", new { area = "" });
            }
            return RedirectToAction(nameof(Login));
        }

        public async Task<IActionResult> Logout()
        {
            await _securityApplicationService.Logout();

            return RedirectToAction(nameof(Login));
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(LoginViewModel vm)
        {
            await _securityApplicationService.RegisterAndLogin(vm);

            return RedirectToAction("Index", "Products", new { area = "" });
        }
    }
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using a5pwt_ctvrtek.Application.ApplicationServices.Carts;
using a5pwt_ctvrtek.Application.ApplicationServices.Security;
using a5pwt_ctvrtek.Domain.Constants;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Controllers
{
    public class CartsController : Controller
    {
        private readonly ICartApplicationService _cartApplicationService;
        private readonly ISecurityApplicationService _securityApplicationService;

        public CartsController(ICartApplicationService cartApplicationService,
            ISecurityApplicationService securityApplicationService)
        {
            _cartApplicationService = cartApplicationService;
            _securityApplicationService = securityApplicationService;
        }

        public async Task<IActionResult> Index()
        {
            var vm = _cartApplicationService.GetIndexViewModel(GetOrCreateTrackingCode());
            var user = await _securityApplicationService.GetCurrentUser(User);
            if (user != null)
            {
                vm.UserID = user.Id;
                vm.UserEmail = user.Email;
            }

            return View(vm);
        }

        [HttpPost]
        public JsonResult AddToCart(int id, int amount)
        {
            var cartItem = _cartApplicationService.AddToCart(id, amount, GetOrCreateTrackingCode());

            return Json(cartItem);
        }

        [HttpPost]
        public JsonResult RemoveFromCart(int id)
        {
            _cartApplicationService.RemoveFromCart(id, GetOrCreateTrackingCode());
            return Json("success");
        }

        private string GetOrCreateTrackingCode()
        {
            var utc = Request.Cookies[Cookies.UserTrackingCode];
            if (utc != null)
                return utc;

            var guid = Guid.NewGuid().ToString();
            var options = new CookieOptions();
            options.Expires = DateTime.Now.AddYears(1);

            Response.Cookies.Append(Cookies.UserTrackingCode, guid, options);
            return guid;
        }
    }
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using a5pwt_ctvrtek.Application.ApplicationServices.Orders;
using a5pwt_ctvrtek.Application.ApplicationServices.Security;
using a5pwt_ctvrtek.Domain.Constants;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrderApplicationService _orderApplicationService;
        private readonly ISecurityApplicationService _securityApplicationService;

        public OrdersController(IOrderApplicationService orderApplicationService,
            ISecurityApplicationService securityApplicationService)
        {
            _orderApplicationService = orderApplicationService;
            _securityApplicationService = securityApplicationService;
        }

        public async Task<IActionResult> Create()
        {
            var user = await _securityApplicationService.GetCurrentUser(User);
            _orderApplicationService.CreateOrder(
                user.Id,
                Request.Cookies[Cookies.UserTrackingCode]
                );

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Index()
        {
            var user = await _securityApplicationService.GetCurrentUser(User);
            var vm = _orderApplicationService.GetIndexViewModel(user.Id);
            return View(vm);
        }
    }
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using a5pwt_ctvrtek.Application.ApplicationServices.Products;
using Microsoft.AspNetCore.Mvc;

namespace a5pwt_ctvrtek.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductApplicationService _productApplicationService;

        public ProductsController(IProductApplicationService productApplicationService)
        {
            _productApplicationService = productApplicationService;
        }

        public IActionResult Index()
        {
            var vm = _productApplicationService.GetIndexViewModel();
            return View(vm);
        }

        public IActionResult Detail(int id)
        {
            var vm = _productApplicationService.GetProductViewModel(id);
            return View(vm);
        }
    }
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Views/Products/Edit.cshtml
@model a5pwt_ctvrtek.Application.ViewModels.Products.ProductViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ProductViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Views/Products/Index.cshtml
@model a5pwt_ctvrtek.Application.ViewModels.Products.IndexViewModel

@{
    ViewData["Title"] = "Index";
}
<h2>Products</h2>

<div class="col-lg-1 col-lg-offset-11">
    <button type="button" class="btn btn-default btn-insert"
            data-toggle="tooltip" data-placement="bottom"
            title="Přidat">
        <i class="glyphicon-plus"></i>
    </button>
</div>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Image</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Products) {
        <tr>
            <td class="id">@item.ID</td>
            <td class="name">@item.Name</td>
            <td class="price">@item.Price</td>
            <td class="imageurl"><img class="product-thumbnail" src="@item.ImageURL" alt="@item.Name" /></td>
            <td class="actions">
                @*<a asp-area="Admin" asp-controller="Products" asp-action="Edit" asp-route-id="@item.ID">Editovat</a>*@
                <button class="btn btn-primary btn-edit">Editovat</button> |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
}
    </tbody>
</table>

@section scripts{ 
<script>
    $(document).ready(() => {
        $('.btn-insert').click(createRow);
        $(document).on('click', '.btn-discard', discard);
        $(document).on('click', '.btn-save', insert);
        $(document).on('click', '.btn-edit', edit);
        $(document).on('click', '.btn-saveedit', saveEdit);
    });
    
    function edit() {
        const row = $(this).closest('tr');
        let id = row.find('.id').text(),
            name = row.find('.name').text(),
            price = row.find('.price').text(),
            imageurl = row.find('.imageurl img').attr('src');

        row.find('.id').html('<input class="form-control" name="ID" type="number" value="' + parseInt(id) + '" readonly />');
        row.find('.name').html('<input class="form-control" name="Name" type="text" value="' + name + '" />');
        row.find('.price').html('<input class="form-control" name="Price" type="number" value="' + parseFloat(price) + '" />');
        row.find('.imageurl').html('<input class="form-control" name="Image" type="file" />' +
            '<input name="ImageURL" type="hidden" value="' + imageurl + '" />');
        row.find('.actions').html('<button type="button" class="btn btn-primary btn-saveedit">Uložit</button>');
    }

    function createRow() {
        const table = $('table tbody');
        table.prepend(
            '<tr>' +
                '<td class="id" data-id=""></td>' +
                '<td class="name" data-name="">' +
                    '<input type="text" class="form-control" name="Name" />' +
                '</td>' +
                '<td class="price" data-price="">' +
                    '<input type="number" class="form-control" name="Price" />' +
                '</td>' +
                '<td class="imageurl" data-image-url="">' +
                    '<input type="file" class="form-control" name="Image" />' +
                '</td>' +
                '<td>' +
                    '<button type="button" class="btn btn-primary btn-save">Uložit</button>' +
                    '<button type="button" class="btn btn-danger btn-discard">Zahodit</button>' +
                '</td>' +

            '</tr>'
        );
    }

    function discard() {
        const row = $(this).closest('tr');
        row.remove();
    }

    function insert() {
        sendData('@Url.Action("Insert")', this);
    }
    
    function saveEdit() {
        sendData('@Url.Action("Edit")', this);
    }

    function sendData(actionUrl, context) {
        const row = $(context).closest('tr');
        const inputs = row.find('input');

        const form = document.createElement('form');
        inputs.map((i, input) => form.append(input.cloneNode()));
        const formData = new FormData(form);

        $.ajax({
            method: 'POST',
            url: actionUrl,
            data: formData,
            contentType: false,
            processData: false,
            success: function (data) {
                row.find('.id').text(data.ID);
                row.find('.name').html(data.name);
                row.find('.price').html(data.price);
                row.find('.imageurl').html(createImg(data.imageURL));
            }
        });
    }

    function createImg(imageURL) {
        const img = document.createElement('img');
        img.src = imageURL;
        img.classList.add('product-thumbnail');
        return img;
    }

</script>
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Views/Products/Insert.cshtml
@model a5pwt_ctvrtek.Application.ViewModels.Products.ProductViewModel

@{
    ViewData["Title"] = "Insert";
}

<h2>Insert</h2>

<h4>ProductViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Insert" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Views/Security/Login.cshtml
@model a5pwt_ctvrtek.Application.ViewModels.Security.LoginViewModel

@{
    ViewData["Title"] = "Login";
}

<h2>Login</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="RememberMe" /> @Html.DisplayNameFor(model => model.RememberMe)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Register">Register</a>
</div>

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Views/Security/Register.cshtml
@model a5pwt_ctvrtek.Application.ViewModels.Security.LoginViewModel

@{
    ViewData["Title"] = "Register";
}

<h2>Register</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

a5pwt_ctvrtek/a5pwt_ctvrtek/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - a5pwt_ctvrtek</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Products" asp-action="Index" class="navbar-brand">Products</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="Admin" asp-controller="Products" asp-action="Index">Admin</a></li>
                    <li><a asp-area="Admin" asp-controller="Security" asp-action="Logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - a5pwt_ctvrtek</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

a5pwt_ctvrtek/a5pwt_ctvrtek/Views/Carts/Index.cshtml
@model a5pwt_ctvrtek.Application.ViewModels.Carts.IndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Košík</h2>

<table class="table">
    <thead>
        <tr>
            <th>
               Produkt
            </th>
            <th>
               Obrázek
            </th>
            <th>
               Množství
            </th>
            <th>
               Cena za kus
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.CartItems) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                <img class="product-thumbnail" src="@item.ImageURL" alt="@item.ProductName" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
        </tr>
}
    </tbody>
</table>
<h3>
    Celkem: @Model.Total Kč
</h3>

@if(Model.CartItems.Count > 0 && Model.UserID.HasValue)
{
    <a asp-controller="Orders" asp-action="Create" class="btn btn-primary">Objednat</a>
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Views/Products/Detail.cshtml
@model a5pwt_ctvrtek.Application.ViewModels.Products.ProductViewModel

@{
    ViewData["Title"] = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>@Model.Name</h4>
    <hr />
    <div class="row">
        <div class="col-md-5">
            <img src="@Model.ImageURL" alt="@Model.Name" style="max-height:200px;" />
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Price)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Price)
                </dd>
            </dl>
        </div>
        <div class="col-md-2">
            <input class="form-control" type="number" value="1" />
            <button id="add-to-cart" data-id="@Model.ID" class="btn btn-primary">Přidat do košíku</button>

            <div class="alert alert-success" id="success-alert" style="display:none;">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong>Added!</strong>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script>
    $(document).ready(() => {
        $('#add-to-cart').click(addToCart);
    });

    function addToCart() {
        var id = $(this).data('id');
        var amount = $(this).closest('div').find('input').val();

        $.ajax({
            method: 'POST',
            url: '@Url.Action("AddToCart", "Carts")',
            data: {id: id, amount: amount},
            success: function () {
                $("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
                    $("#success-alert").slideUp(500);
                });
            }
        })
    }
    </script>
}

a5pwt_ctvrtek/a5pwt_ctvrtek/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - a5pwt_ctvrtek</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Products" asp-action="Index" class="navbar-brand">Products</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="Admin" asp-controller="Security" asp-action="Login">Login</a></li>
                    <li>
                        <a asp-controller="Carts" asp-action="Index">
                            <i class="glyphicon glyphicon-shopping-cart"></i>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Orders" asp-action="Index">
                            <i class="glyphicon glyphicon-list"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - a5pwt_ctvrtek</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>